In [1]:
import numpy as np

In [35]:
l = "We Are Learning Data Science Library"
l

'We Are Learning Data Science Library'

In [6]:
np.char.array(l)

chararray(['We Are Learning Data Science Library'], dtype='<U36')

In [ ]:
np.char.capitalize(l)

In [28]:
a = np.char.center(l,50)
a

array('       We Are Learning Data Science Library       ', dtype='<U50')

In [ ]:
np.char.center(l,50,"*")

In [7]:
np.char.count(l,"a")


array(4)

In [8]:
np.char.count(l,"l")

array(0)

In [5]:
np.char.count(l,"l")

array(0)

In [9]:
np.char.find(l,"a")

array(9)

In [10]:
np.char.endswith(l,"y")

array(True)

In [11]:
np.char.lower(l)

array('we are learning data science library', dtype='<U36')

In [12]:
np.char.upper(l)

array('WE ARE LEARNING DATA SCIENCE LIBRARY', dtype='<U36')

In [13]:
np.char.title(l)

array('We Are Learning Data Science Library', dtype='<U36')

In [14]:
np.char.bool_(l)

True

In [16]:
np.char.islower(l)

array(False)

In [17]:
np.char.isupper(l)

array(False)

In [18]:
l = ['fcd','vfg','hjk']
np.char.upper(l)

array(['FCD', 'VFG', 'HJK'], dtype='<U3')

In [19]:
l = ['ADG','GHJ','TYU','RTE']
np.char.lower(l)

array(['adg', 'ghj', 'tyu', 'rte'], dtype='<U3')

In [22]:
l = ['vbh','xgf','rtu','jkh','klj',1,'cdf',3,'jkl',4,5,'fnk']
np.char.isnumeric(l)

array([False, False, False, False, False,  True, False,  True, False,
        True,  True, False])

In [23]:
l

['vbh', 'xgf', 'rtu', 'jkh', 'klj', 1, 'cdf', 3, 'jkl', 4, 5, 'fnk']

In [45]:
a

array('       We Are Learning Data Science Library       ', dtype='<U50')

In [31]:
np.char.lstrip(a)

array('We Are Learning Data Science Library       ', dtype='<U50')

In [32]:
np.char.rstrip(a)

array('       We Are Learning Data Science Library', dtype='<U50')

In [33]:
np.char.strip(a)

array('We Are Learning Data Science Library', dtype='<U50')

In [37]:
np.char.multiply(a,2)

array('       We Are Learning Data Science Library              We Are Learning Data Science Library       ',
      dtype='<U100')

In [40]:
np.char.multiply(l,2)

array('We Are Learning Data Science LibraryWe Are Learning Data Science Library',
      dtype='<U72')

In [41]:
np.char.encode(l)

array(b'We Are Learning Data Science Library', dtype='|S36')

In [42]:
np.char.encode(a)

array(b'       We Are Learning Data Science Library       ', dtype='|S50')

In [47]:
np.char.join(a,"")


array('', dtype='<U1')

In [52]:
a = np.char.array("we are learning python")
a

chararray(['we are learning python'], dtype='<U22')

In [53]:
np.char.count(a,"e")

array([3])

In [58]:
l = np.char.array(['neha','sneha','neva','nene'])
l

chararray(['neha', 'sneha', 'neva', 'nene'], dtype='<U5')

In [59]:
np.char.count(l,"ne")

array([1, 1, 1, 2])

In [60]:
np.char.count(l,"n")

array([1, 1, 1, 2])

In [64]:
np.char.rpartition(l,"n")

array([['', 'n', 'eha'],
       ['s', 'n', 'eha'],
       ['', 'n', 'eva'],
       ['ne', 'n', 'e']], dtype='<U3')

In [65]:
np.char.rsplit(l)

array([list(['neha']), list(['sneha']), list(['neva']), list(['nene'])],
      dtype=object)

In [66]:
np.char.asbytes(l)

b"['neha' 'sneha' 'neva' 'nene']"

In [68]:
l = "We Are Learning Data Science Library"
l

'We Are Learning Data Science Library'

In [70]:
a = np.char.encode(l)
a

array(b'We Are Learning Data Science Library', dtype='|S36')

In [71]:
np.char.decode(a)

array('We Are Learning Data Science Library', dtype='<U36')

In [2]:
import numpy as np

In [3]:
l = "learning python"

In [4]:
np.char.count(l,"n")

array(3)